# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38f56cf2fa4e50742f2f238b954ac78d9b3b433ba3b7be90795fb02c76df507daca80c7cb1eace0adc7c1611e1647e59b52b2853a218d9f8b93cb256f5f9a161

test:
  secret_key_base: 8e65361748138416887a22903f7bdf27cf0618081386da53ef46ead03879c8dc1498503f24114dd38a2f37c4fd48c9e37ece9aea4da99747752721c8ab9e124d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
